# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1826355ec6ab66d9b9156b56f830f4c4846c4ca52a6bb3d5887d00531e6b7f602b4e8104d3118c30f89fc66a389ef8259645bce5b9649a352b9b4e232c69c34

test:
  secret_key_base: 398743c6a1141a163ca6134550184bff70e4dc2b8e0e1b580bcd021dff258eace8e0fd6e733ce99afff54b2190a469eae6eb8b2918fd018fb26687a5a340dbd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
